# TP17 - BlueVisionary

# Iteration 1 - Data Cleaning and Wrangling

In [ ]:
# Installing libraries

#!pip install requests pandas
#!pip install pandas
#!pip install numpy
#!pip install csv
#!pip install os
#!pip install matplotlib
#!pip install html
#!pip install json

In [4]:
# Importing Libraries

import pandas as pd
import csv
import geojson
import matplotlib as plt
import os
import requests
import time
import re
import html
import json
import geopandas as gpd
import warnings

In [5]:
# Suppress any warning
warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")

# Loading the CSV files

In [6]:
# Get the current working directory (directory of the script)
current_dir = os.getcwd()

# Construct the relative path to the CSV file
species_sign_1 = os.path.join(current_dir, "Species_significance.csv")

# Construct the relative path to the CSV file
threat_species_1 = os.path.join(current_dir, "Threatened_state.csv")

# Construct the relative path to the Excel file
epbc_threat_1 = os.path.join(current_dir, "EPBC_Act_Threatened_Species.csv")

In [7]:
# Reading Species significance data from CSV
threat_df = pd.read_csv(species_sign_1)

# Reading Threatened state
threat_state_df = pd.read_csv(threat_species_1)

# Reading EPBC_Act_Threatened_Species
threat_df_find_status_values = pd.read_csv(epbc_threat_1)

In [8]:
# Displaying datafame
threat_df.head()

,OBJECTID,LISTED_TAXON_ID,MAP_TAXON_ID,SCIENTIFIC_NAME,VERNACULAR_NAME,THREATENED_STATUS,MIGRATORY_STATUS,MARINE,CETACEAN,PRESENCE_RANK,...,TAXON_PHYLUM,TAXON_KINGDOM,OTHER_IDS,CELL_SIZE,REGIONS,ATTRIBUTION,SPRAT_PROFILE,SHAPE__Area,SHAPE__Length,GlobalID
0,1,12136,12136,Thomasia montana,Hill Thomasia,Vulnerable,NaN,NaN,NaN,2,...,Magnoliophyta,Plantae,NaN,0.01,WA,Species of National Environmental Significance...,http://www.environment.gov.au/cgi-bin/sprat/pu...,1.548804e+09,7.920967e+05,cd0abb4e-3c63-402d-a200-425dddac46c2
1,2,86125,86125,Atalaya brevialata,NaN,Critically Endangered,NaN,NaN,NaN,2,...,Magnoliophyta,Plantae,85262,0.01,NT,Species of National Environmental Significance...,http://www.environment.gov.au/cgi-bin/sprat/pu...,5.714192e+07,3.617255e+04,73d86866-f493-45d6-9621-5293bd9987e0
2,3,86125,86125,Atalaya brevialata,NaN,Critically Endangered,NaN,NaN,NaN,1,...,Magnoliophyta,Plantae,85262,0.01,NT,Species of National Environmental Significance...,http://www.environment.gov.au/cgi-bin/sprat/pu...,3.683180e+07,5.866158e+04,92d5b0cf-dd12-49a0-9807-50102d35f986
3,4,66237,66237,Hippocampus kuda,"Spotted Seahorse, Yellow Seahorse",NaN,NaN,Listed,NaN,1,...,Chordata,Animalia,NaN,0.01,NT; QLD; NSW; WA; CMA,Species of National Environmental Significance...,http://www.environment.gov.au/cgi-bin/sprat/pu...,2.500755e+12,3.667640e+07,478826a8-9843-4c1c-9b94-c729d9a27d92
4,5,84785,84785,Harrisoniascincus zia,Rainforest Cool-skink,Vulnerable,NaN,NaN,NaN,1,...,Chordata,Animalia,"1376,59707",0.01,QLD; NSW,Species of National Environmental Significance...,http://www.environment.gov.au/cgi-bin/sprat/pu...,1.017788e+10,8.614064e+06,dbd9df17-a726-4ba1-8c5e-d27348279dc9

In [9]:
# Displaying datafame
threat_state_df.head()

,Scientific Name,Common Name,Current Scientific Name,Threatened status,ACT,NSW,NT,QLD,SA,TAS,...,Profile,Date extracted,NSL Name,Family,Genus,Species,Infraspecific Rank,Infraspecies,Species Author,Infraspecies Author
0,Abutilon julianae,Norfolk Island Abutilon,-,Critically Endangered,-,-,-,-,-,-,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,2024-Jul-24,https://id.biodiversity.org.au/name/apni/56543,Malvaceae,Abutilon,julianae,-,-,Endl.,-
1,Acacia ammophila,-,-,Vulnerable,-,-,-,Yes,-,-,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,2024-Jul-24,https://id.biodiversity.org.au/name/apni/58340,Fabaceae,Acacia,ammophila,-,-,Pedley,-
2,Acacia anomala,"Grass Wattle, Chittering Grass Wattle",-,Vulnerable,-,-,-,-,-,-,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,2024-Jul-24,https://id.biodiversity.org.au/name/apni/58556,Fabaceae,Acacia,anomala,-,-,C.A.Gardner ex Court,-
3,Acacia aphylla,Leafless Rock Wattle,-,Vulnerable,-,-,-,-,-,-,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,2024-Jul-24,https://id.biodiversity.org.au/name/apni/58565,Fabaceae,Acacia,aphylla,-,-,Maslin,-
4,Acacia aprica,Blunt Wattle,-,Endangered,-,-,-,-,-,-,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,2024-Jul-24,https://id.biodiversity.org.au/name/apni/149911,Fabaceae,Acacia,aprica,-,-,Maslin A.R.Chapman,-

In [10]:
# Displaying datafame
threat_df_find_status_values.head()

,Supplied Name,guid,scientificName,family,kingdom,genus,raw_scientificName,vernacularName,raw.family,status,sourceStatus
0,Senecio georgianus,https://id.biodiversity.org.au/node/apni/2915181,Senecio georgianus,Asteraceae,Plantae,Senecio,Senecio georgianus,Grey Groundsel,Asteraceae,Extinct,Extinct
1,Lagorchestes hirsutus hirsutus,https://biodiversity.org.au/afd/taxa/43b0abb2-...,Lagorchestes hirsutus hirsutus,Macropodidae,Animalia,Lagorchestes,Lagorchestes hirsutus hirsutus,"Rufous Hare-wallaby (south-western), Woorap",Macropodidae,Extinct,Extinct
2,Litoria raniformis,https://biodiversity.org.au/afd/taxa/89a7a289-...,Litoria raniformis,Pelodryadidae,Animalia,Litoria,Litoria raniformis,"Southern Bell Frog,, Growling Grass Frog, Gree...",Pelodryadidae,Vulnerable,Vulnerable
3,Epacris exserta,https://id.biodiversity.org.au/node/apni/2893201,Epacris exserta,Ericaceae,Plantae,Epacris,Epacris exserta,South Esk Heath,Epacridaceae,Endangered,Endangered
4,Asplenium wildii,https://id.biodiversity.org.au/taxon/apni/5143...,Hymenasplenium wildii,Aspleniaceae,Plantae,Asplenium,Asplenium wildii,-,Aspleniaceae,Vulnerable,Vulnerable

# Cleaning and Wrangling Threatened Species CSV

In [4]:
threat_df.head()

,OBJECTID,LISTED_TAXON_ID,MAP_TAXON_ID,SCIENTIFIC_NAME,VERNACULAR_NAME,THREATENED_STATUS,MIGRATORY_STATUS,MARINE,CETACEAN,PRESENCE_RANK,...,TAXON_PHYLUM,TAXON_KINGDOM,OTHER_IDS,CELL_SIZE,REGIONS,ATTRIBUTION,SPRAT_PROFILE,SHAPE__Area,SHAPE__Length,GlobalID
0,1,12136,12136,Thomasia montana,Hill Thomasia,Vulnerable,NaN,NaN,NaN,2,...,Magnoliophyta,Plantae,NaN,0.01,WA,Species of National Environmental Significance...,http://www.environment.gov.au/cgi-bin/sprat/pu...,1.548804e+09,7.920967e+05,cd0abb4e-3c63-402d-a200-425dddac46c2
1,2,86125,86125,Atalaya brevialata,NaN,Critically Endangered,NaN,NaN,NaN,2,...,Magnoliophyta,Plantae,85262,0.01,NT,Species of National Environmental Significance...,http://www.environment.gov.au/cgi-bin/sprat/pu...,5.714192e+07,3.617255e+04,73d86866-f493-45d6-9621-5293bd9987e0
2,3,86125,86125,Atalaya brevialata,NaN,Critically Endangered,NaN,NaN,NaN,1,...,Magnoliophyta,Plantae,85262,0.01,NT,Species of National Environmental Significance...,http://www.environment.gov.au/cgi-bin/sprat/pu...,3.683180e+07,5.866158e+04,92d5b0cf-dd12-49a0-9807-50102d35f986
3,4,66237,66237,Hippocampus kuda,"Spotted Seahorse, Yellow Seahorse",NaN,NaN,Listed,NaN,1,...,Chordata,Animalia,NaN,0.01,NT; QLD; NSW; WA; CMA,Species of National Environmental Significance...,http://www.environment.gov.au/cgi-bin/sprat/pu...,2.500755e+12,3.667640e+07,478826a8-9843-4c1c-9b94-c729d9a27d92
4,5,84785,84785,Harrisoniascincus zia,Rainforest Cool-skink,Vulnerable,NaN,NaN,NaN,1,...,Chordata,Animalia,"1376,59707",0.01,QLD; NSW,Species of National Environmental Significance...,http://www.environment.gov.au/cgi-bin/sprat/pu...,1.017788e+10,8.614064e+06,dbd9df17-a726-4ba1-8c5e-d27348279dc9

In [13]:
# Removing Unnecessary Columns

Cols_threat = ["OBJECTID","MAP_TAXON_ID", "MIGRATORY_STATUS","CETACEAN","OTHER_IDS","PRESENCE_RANK","PRESENCE_CATEGORY","CELL_SIZE","ATTRIBUTION"
               ,"SHAPE__Area","SHAPE__Length","GlobalID"]

threat_df_filtered = threat_df.drop(columns=Cols_threat)

In [14]:
# Filtering Marine species excluding birds
threat_df_filtered_marine = threat_df_filtered[(threat_df_filtered["MARINE"]== "Listed") & (threat_df_filtered["TAXON_GROUP"] != "birds")]

In [17]:
threat_df_filtered_marine.head(50)

,LISTED_TAXON_ID,SCIENTIFIC_NAME,VERNACULAR_NAME,THREATENED_STATUS,MARINE,EXTRACT_DATE,TAXON_GROUP,TAXON_FAMILY,TAXON_ORDER,TAXON_CLASS,TAXON_PHYLUM,TAXON_KINGDOM,REGIONS,SPRAT_PROFILE
3,66237,Hippocampus kuda,"Spotted Seahorse, Yellow Seahorse",NaN,Listed,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,Animalia,NT; QLD; NSW; WA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
331,66223,Halicampus mataafae,Samoan Pipefish,NaN,Listed,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,Animalia,QLD; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
561,1090,Parahydrophis mertoni,"Arafura Smooth Sea Snake, Northern Mangrove Se...",NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,Reptilia,Chordata,Animalia,NT; QLD; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
566,66705,Hippocampus minotaur,Bullneck Seahorse,NaN,Listed,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,Animalia,NSW; TAS; VIC; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
619,1118,Aipysurus foliosquama,"Leaf-scaled Sea Snake, Leaf-scaled Seasnake",Critically Endangered,Listed,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,Reptilia,Chordata,Animalia,WA; ACI; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
620,1118,Aipysurus foliosquama,"Leaf-scaled Sea Snake, Leaf-scaled Seasnake",Critically Endangered,Listed,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,Reptilia,Chordata,Animalia,WA; ACI; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
621,1119,Aipysurus fuscus,Dusky Sea Snake,NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,Reptilia,Chordata,Animalia,NT; WA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
623,1116,Aipysurus duboisii,"Dubois' Sea Snake, Dubois' Seasnake, Reef Shal...",NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,Reptilia,Chordata,Animalia,NT; QLD; WA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
624,1117,Aipysurus eydouxii,Spine-tailed Sea Snake,NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,Reptilia,Chordata,Animalia,NT; QLD; WA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
646,1100,Hydrelaps darwiniensis,"Port Darwin Sea Snake, Black-ringed Mangrove S...",NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,Reptilia,Chordata,Animalia,NT; QLD; WA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
647,1101,Hydrophis atriceps,Black-headed Sea Snake,NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,Reptilia,Chordata,Animalia,NT; QLD; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
670,1115,Aipysurus apraefrontalis,"Short-nosed Sea Snake, Short-nosed Seasnake",Critically Endangered,Listed,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,Reptilia,Chordata,Animalia,WA; ACI; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
671,1103,Hydrophis caerulescens,Dwarf Sea Snake,NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,Reptilia,Chordata,Animalia,QLD; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
686,1112,Hydrophis pacificus,"Pacific Sea Snake, Large-headed Sea Snake",NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,Reptilia,Chordata,Animalia,NT; QLD; WA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
689,66722,Hippocampus subelongatus,West Australian Seahorse,NaN,Listed,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,Animalia,WA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
690,66723,Hippocampus kelloggi,"Kellogg's Seahorse, Great Seahorse",NaN,Listed,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,Animalia,QLD; NSW; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
773,1126,Enhydrina schistosa,Beaked Sea Snake,NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Hydrophiidae,Squamata,Reptilia,Chordata,Animalia,NT; QLD; WA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
774,1127,Ephalophis greyi,Mangrove Sea Snake,NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,Reptilia,Chordata,Animalia,WA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
821,1121,Aipysurus tenuis,"Brown-lined Sea Snake, Mjoberg's Sea Snake",NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,Reptilia,Chordata,Animalia,WA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
822,1122,Astrotia stokesii,Stokes' Sea Snake,NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Hydrophiidae,Squamata,Reptilia,Chordata,Animalia,NT; QLD; NSW; WA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
823,1123,Disteira kingii,Spectacled Sea Snake,NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Hydrophiidae,Squamata,Reptilia,Chordata,Animalia,NT; QLD; WA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
860,25927,Hydrophis vorisi,Estuarine Sea Snake,NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,Reptilia,Chordata,Animalia,QLD; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
864,1092,Laticauda colubrina,Yellow-lipped Sea Krait,NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Laticaudidae,Squamata,Reptilia,Chordata,Animalia,QLD; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
865,1093,Laticauda laticaudata,a sea krait,NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Laticaudidae,Squamata,Reptilia,Chordata,Animalia,QLD; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
895,1119,Aipysurus fuscus,Dusky Sea Snake,NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,Reptilia,Chordata,Animalia,NT; WA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
896,1120,Aipysurus laevis,"Olive Sea Snake, Olive-brown Sea Snake",NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,Reptilia,Chordata,Animalia,NT; QLD; WA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
897,1124,Disteira major,Olive-headed Sea Snake,NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Hydrophiidae,Squamata,Reptilia,Chordata,Animalia,NT; QLD; WA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
898,1125,Emydocephalus annulatus,Eastern Turtle-headed Sea Snake,NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,Reptilia,Chordata,Animalia,NT; QLD; WA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
1085,66274,Solegnathus robustus,"Robust Pipehorse, Robust Spiny Pipehorse",NaN,Listed,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,Animalia,NSW; TAS; VIC; SA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
1136,66061,Aipysurus pooleorum,Shark Bay Sea Snake,NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,Reptilia,Chordata,Animalia,WA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
1198,66249,Lissocampus caudalis,"Australian Smooth Pipefish, Smooth Pipefish",NaN,Listed,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,Animalia,TAS; VIC; WA; SA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
1267,66283,Vanacampus margaritifer,Mother-of-pearl Pipefish,NaN,Listed,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,Animalia,QLD; NSW; TAS; VIC; WA; SA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
1270,66206,Cosmocampus banneri,Roughridge Pipefish,NaN,Listed,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,Animalia,WA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
1272,66218,Halicampus boothae,Booth's Pipefish,NaN,Listed,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,Animalia,NSW; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
1273,66219,Halicampus brocki,Brock's Pipefish,NaN,Listed,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,Animalia,NT; QLD; WA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
1363,21,Arctocephalus pusillus,"Australian Fur-seal, Australo-African Fur-seal",NaN,Listed,2/15/2024 12:00:00 AM,mammals,Otariidae,Pinnipedia,Mammalia,Chordata,Animalia,NSW; TAS; VIC; SA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
1364,22,Neophoca cinerea,"Australian Sea-lion, Australian Sea Lion",Endangered,Listed,2/15/2024 12:00:00 AM,mammals,Otariidae,Pinnipedia,Mammalia,Chordata,Animalia,WA; SA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
1365,22,Neophoca cinerea,"Australian Sea-lion, Australian Sea Lion",Endangered,Listed,2/15/2024 12:00:00 AM,mammals,Otariidae,Pinnipedia,Mammalia,Chordata,Animalia,WA; SA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
1366,26,Mirounga leonina,Southern Elephant Seal,Vulnerable,Listed,2/15/2024 12:00:00 AM,mammals,Phocidae,Pinnipedia,Mammalia,Chordata,Animalia,NSW; TAS; VIC; WA; SA; HMI; AAT; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
1367,26,Mirounga leonina,Southern Elephant Seal,Vulnerable,Listed,2/15/2024 12:00:00 AM,mammals,Phocidae,Pinnipedia,Mammalia,Chordata,Animalia,NSW; TAS; VIC; WA; SA; HMI; AAT; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
1370,28,Dugong dugon,Dugong,NaN,Listed,2/15/2024 12:00:00 AM,mammals,Dugongidae,Sirenia,Mammalia,Chordata,Animalia,NT; QLD; NSW; WA; ACI; CSI; JBT; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
1371,28,Dugong dugon,Dugong,NaN,Listed,2/15/2024 12:00:00 AM,mammals,Dugongidae,Sirenia,Mammalia,Chordata,Animalia,NT; QLD; NSW; WA; ACI; CSI; JBT; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
1787,20,Arctocephalus forsteri,"Long-nosed Fur-seal, New Zealand Fur-seal",NaN,Listed,2/15/2024 12:00:00 AM,mammals,Otariidae,Pinnipedia,Mammalia,Chordata,Animalia,NSW; TAS; VIC; WA; SA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
1789,20,Arctocephalus forsteri,"Long-nosed Fur-seal, New Zealand Fur-seal",NaN,Listed,2/15/2024 12:00:00 AM,mammals,Otariidae,Pinnipedia,Mammalia,Chordata,Animalia,NSW; TAS; VIC; WA; SA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
1790,21,Arctocephalus pusillus,"Australian Fur-seal, Australo-African Fur-seal",NaN,Listed,2/15/2024 12:00:00 AM,mammals,Otariidae,Pinnipedia,Mammalia,Chordata,Animalia,NSW; TAS; VIC; SA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
1791,66270,Siokunichthys breviceps,"Softcoral Pipefish, Soft-coral Pipefish",NaN,Listed,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,Animalia,QLD; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
1795,66269,Pugnaso curtirostris,"Pugnose Pipefish, Pug-nosed Pipefish",NaN,Listed,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,Animalia,TAS; VIC; WA; SA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
1796,66264,Nannocampus subosseus,"Bonyhead Pipefish, Bony-headed Pipefish",NaN,Listed,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,Animalia,WA; SA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
1797,66265,Notiocampus ruber,Red Pipefish,NaN,Listed,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,Animalia,NSW; TAS; VIC; WA; SA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...
1811,66281,Trachyrhamphus longirostris,"Straightstick Pipefish, Long-nosed Pipefish, S...",NaN,Listed,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,Animalia,NT; QLD; WA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...

In [18]:
# Removing Duplicates based on Listed Taxon id
threat_df_filtered_marine_nodups = threat_df_filtered_marine.drop_duplicates(subset="LISTED_TAXON_ID")

In [19]:
# checking the datatypes of each attribute
threat_df_filtered_marine_nodups.info()

<class 'pandas.core.frame.DataFrame'>
Index: 159 entries, 3 to 4106
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   LISTED_TAXON_ID    159 non-null    int64
 1   SCIENTIFIC_NAME    159 non-null    object
 2   VERNACULAR_NAME    158 non-null    object
 3   THREATENED_STATUS  12 non-null     object
 4   MARINE             159 non-null    object
 5   EXTRACT_DATE       159 non-null    object
 6   TAXON_GROUP        159 non-null    object
 7   TAXON_FAMILY       159 non-null    object
 8   TAXON_ORDER        159 non-null    object
 9   TAXON_CLASS        159 non-null    object
 10  TAXON_PHYLUM       159 non-null    object
 11  TAXON_KINGDOM      159 non-null    object
 12  REGIONS            159 non-null    object
 13  SPRAT_PROFILE      159 non-null    object
dtypes: int64(1), object(13)
memory usage: 18.6+ KB

# Feature Extraction

In [21]:
# Creating states columns

# Convert REGIONS to string and filling all NaN with an empty string
threat_df_filtered_marine_nodups['REGIONS'] = threat_df_filtered_marine_nodups['REGIONS'].fillna('').astype(str)

# List of states
regions = ['ACT', 'NSW', 'NT', 'QLD', 'SA', 'TAS', 'VIC', 'WA']

# Create the region columns and fill with 1 or 0 based on presence in the REGIONS column
for region in regions:
    threat_df_filtered_marine_nodups[region] = threat_df_filtered_marine_nodups['REGIONS'].apply(lambda x: 1 if region in x else 0)

# Display the resulting DataFrame
threat_df_filtered_marine_nodups.head()

/var/folders/pd/18kkdnhj7vj2pjwwl48qv_x00000gn/T/ipykernel_95109/997547738.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  threat_df_filtered_marine_nodups['REGIONS'] = threat_df_filtered_marine_nodups['REGIONS'].fillna('').astype(str)
/var/folders/pd/18kkdnhj7vj2pjwwl48qv_x00000gn/T/ipykernel_95109/997547738.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  threat_df_filtered_marine_nodups[region] = threat_df_filtered_marine_nodups['REGIONS'].apply(lambda x: 1 if region in x else 0)

,LISTED_TAXON_ID,SCIENTIFIC_NAME,VERNACULAR_NAME,THREATENED_STATUS,MARINE,EXTRACT_DATE,TAXON_GROUP,TAXON_FAMILY,TAXON_ORDER,TAXON_CLASS,...,REGIONS,SPRAT_PROFILE,ACT,NSW,NT,QLD,SA,TAS,VIC,WA
3,66237,Hippocampus kuda,"Spotted Seahorse, Yellow Seahorse",NaN,Listed,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,...,NT; QLD; NSW; WA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,1,1,1,0,0,0,1
331,66223,Halicampus mataafae,Samoan Pipefish,NaN,Listed,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,...,QLD; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,0,1,0,0,0,0
561,1090,Parahydrophis mertoni,"Arafura Smooth Sea Snake, Northern Mangrove Se...",NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,Reptilia,...,NT; QLD; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,1,1,0,0,0,0
566,66705,Hippocampus minotaur,Bullneck Seahorse,NaN,Listed,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,...,NSW; TAS; VIC; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,1,0,0,0,1,1,0
619,1118,Aipysurus foliosquama,"Leaf-scaled Sea Snake, Leaf-scaled Seasnake",Critically Endangered,Listed,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,Reptilia,...,WA; ACI; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4004,66190,Bulbonaricus davaoensis,Davao Pughead Pipefish,NaN,Listed,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,...,QLD; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,0,1,0,0,0,0
4005,66191,Campichthys galei,Gale's Pipefish,NaN,Listed,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,...,WA; SA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,0,0,1,0,0,1
4061,66198,Choeroichthys suillus,Pig-snouted Pipefish,NaN,Listed,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,...,NT; QLD; WA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,1,1,0,0,0,1
4102,66241,Hippocampus zebra,Zebra Seahorse,NaN,Listed,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,...,QLD; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,0,1,0,0,0,0
4106,25909,Arctocephalus tropicalis,Subantarctic Fur-seal,Endangered,Listed,2/15/2024 12:00:00 AM,mammals,Otariidae,Pinnipedia,Mammalia,...,QLD; TAS; VIC; WA; SA; HMI; AAT; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,0,1,1,1,1,1

In [22]:
# checking the count of values in all the columns
threat_df_filtered_marine_nodups.count()

LISTED_TAXON_ID      159
SCIENTIFIC_NAME      159
VERNACULAR_NAME      158
THREATENED_STATUS     12
MARINE               159
EXTRACT_DATE         159
TAXON_GROUP          159
TAXON_FAMILY         159
TAXON_ORDER          159
TAXON_CLASS          159
TAXON_PHYLUM         159
TAXON_KINGDOM        159
REGIONS              159
SPRAT_PROFILE        159
ACT                  159
NSW                  159
NT                   159
QLD                  159
SA                   159
TAS                  159
VIC                  159
WA                   159
dtype: int64

# IUCN Redlist Species API

In [ ]:
# Creating a list of all the species based on their scientific name
scientific_names = threat_df_filtered_marine_nodups['SCIENTIFIC_NAME'].tolist()
scientific_names

In [ ]:
# API token from IUCN redlist website
token = "YOUR API TOKEN"

# Finding Conservation Status

In [ ]:
def fetch_species_data_name(species_name, token):
    """
    Function to fetch the conservation status for each species from the list create above
    """
    
    api_url =f"https://apiv3.iucnredlist.org/api/v3/species/{species_name}?token={token}"

    try:
        response = requests.get(api_url, timeout=10)
        response.raise_for_status()
        species_data = response.json()
        if 'result' in species_data and species_data['result']:
            result = species_data['result'][0]
        # Filter results based on the scientific names in the DataFrame
        # Return the relevant fields
            return {
                'scientificName': result.get('scientific_name',species_name),
                'category': result.get('category')
            }
        else:
            print(f"No result found for {species_name}")
            return None
        
    except requests.exceptions.HTTPError as http_err:
        print(f"HTTP error occurred: {http_err}")
        
    except requests.exceptions.ConnectionError as conn_err:
        print(f"Connection error occurred: {conn_err}")
        
    except requests.exceptions.Timeout as timeout_err:
        print(f"Timeout error occurred: {timeout_err}")
        
    except requests.exceptions.RequestException as req_err:
        print(f"An error occurred: {req_err}")
        
    return None

In [ ]:
# List to store fetched conservation data
fetched_data_final_status = []

# Loop through each scientific name list
for species_name in scientific_names:
    species_data = fetch_species_data_name(species_name, token)
    if species_data:
        fetched_data_final_status.append(species_data)
    else:
        # In case no data found, append a row with None
        fetched_data_final_status.append({
            'scientificName': species_name,
            'category': None
        })

# Creating the dataframe from the fetched data
fetched_species_df = pd.DataFrame(fetched_data_final_status )

In [ ]:
# Display the filtered data
fetched_species_df.head(50)

In [ ]:
# Coverting the dataframe to CSV file
fetched_species_df.to_csv('combined_species_data.csv', index=False)

In [24]:
# Read CSV 
new_threat_iucn_data =pd.read_csv("combined_species_data.csv")

In [25]:
new_threat_iucn_data.head(2)

     scientificName category
0  Hippocampus kuda       VU
1   Catharacta skua       LC

In [26]:
new_threat_iucn_data.rename(columns={'scientificName': 'SCIENTIFIC_NAME'}, inplace=True)

In [27]:
new_threat_iucn_data.replace({'category':{'VU':'Vulnerable', 'LC':'Least Concerned', 
                                        'EN':'Endangered', 'CR':'Critically Endangered',
                                        'DD':'Data Deficient','NT': 'Near Threatened'}}, inplace = True)

In [28]:
new_threat_iucn_data.head(2)

    SCIENTIFIC_NAME         category
0  Hippocampus kuda       Vulnerable
1   Catharacta skua  Least Concerned

In [29]:
df_combined_marine_nodups_iucn =  pd.merge(threat_df_filtered_marine_nodups, new_threat_iucn_data, on='SCIENTIFIC_NAME')

In [30]:
df_combined_marine_nodups_iucn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147 entries, 0 to 146
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   LISTED_TAXON_ID    147 non-null    int64
 1   SCIENTIFIC_NAME    147 non-null    object
 2   VERNACULAR_NAME    147 non-null    object
 3   THREATENED_STATUS  12 non-null     object
 4   MARINE             147 non-null    object
 5   EXTRACT_DATE       147 non-null    object
 6   TAXON_GROUP        147 non-null    object
 7   TAXON_FAMILY       147 non-null    object
 8   TAXON_ORDER        147 non-null    object
 9   TAXON_CLASS        147 non-null    object
 10  TAXON_PHYLUM       147 non-null    object
 11  TAXON_KINGDOM      147 non-null    object
 12  REGIONS            147 non-null    object
 13  SPRAT_PROFILE      147 non-null    object
 14  ACT                147 non-null    int64
 15  NSW                147 non-null    int64
 16  NT                 147 non-null    int64
 17  QLD                147 non-null    int64
 18  SA                 147 non-null    int64
 19  TAS                147 non-null    int64
 20  VIC                147 non-null    int64
 21  WA                 147 non-null    int64
 22  category           147 non-null    object
dtypes: int64(9), object(14)
memory usage: 26.5+ KB

In [31]:
df_combined_marine_nodups_iucn.head(10)

,LISTED_TAXON_ID,SCIENTIFIC_NAME,VERNACULAR_NAME,THREATENED_STATUS,MARINE,EXTRACT_DATE,TAXON_GROUP,TAXON_FAMILY,TAXON_ORDER,TAXON_CLASS,...,SPRAT_PROFILE,ACT,NSW,NT,QLD,SA,TAS,VIC,WA,category
0,66237,Hippocampus kuda,"Spotted Seahorse, Yellow Seahorse",NaN,Listed,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,1,1,1,0,0,0,1,Vulnerable
1,66223,Halicampus mataafae,Samoan Pipefish,NaN,Listed,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,0,1,0,0,0,0,Least Concerned
2,1090,Parahydrophis mertoni,"Arafura Smooth Sea Snake, Northern Mangrove Se...",NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,Reptilia,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,1,1,0,0,0,0,Data Deficient
3,66705,Hippocampus minotaur,Bullneck Seahorse,NaN,Listed,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,1,0,0,0,1,1,0,Data Deficient
4,1118,Aipysurus foliosquama,"Leaf-scaled Sea Snake, Leaf-scaled Seasnake",Critically Endangered,Listed,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,Reptilia,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,0,0,0,0,0,1,Data Deficient
5,1119,Aipysurus fuscus,Dusky Sea Snake,NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,Reptilia,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,1,0,0,0,0,1,Endangered
6,1116,Aipysurus duboisii,"Dubois' Sea Snake, Dubois' Seasnake, Reef Shal...",NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,Reptilia,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,1,1,0,0,0,1,Least Concerned
7,1117,Aipysurus eydouxii,Spine-tailed Sea Snake,NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,Reptilia,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,1,1,0,0,0,1,Least Concerned
8,1100,Hydrelaps darwiniensis,"Port Darwin Sea Snake, Black-ringed Mangrove S...",NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,Reptilia,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,1,1,0,0,0,1,Least Concerned
9,1101,Hydrophis atriceps,Black-headed Sea Snake,NaN,Listed,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,Reptilia,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,1,1,0,0,0,0,Least Concerned

In [32]:
# Filling NAN values in THREATENED_STATUS with values from category
df_combined_marine_nodups_iucn['THREATENED_STATUS'] = df_combined_marine_nodups_iucn['THREATENED_STATUS'].fillna(df_combined_marine_nodups_iucn.pop('category'))

In [26]:
df_combined_marine_nodups_iucn.head(10)

,LISTED_TAXON_ID,SCIENTIFIC_NAME,VERNACULAR_NAME,THREATENED_STATUS,MARINE,PRESENCE_CATEGORY,EXTRACT_DATE,TAXON_GROUP,TAXON_FAMILY,TAXON_ORDER,...,REGIONS,SPRAT_PROFILE,ACT,NSW,NT,QLD,SA,TAS,VIC,WA
0,66237.0,Hippocampus kuda,"Spotted Seahorse, Yellow Seahorse",Vulnerable,Listed,Species or species habitat may occur,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,...,NT; QLD; NSW; WA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,1,1,1,0,0,0,1
1,59472.0,Catharacta skua,Great Skua,Least Concerned,Listed,Species or species habitat may occur,2/15/2024 12:00:00 AM,birds,Laridae,Charadriiformes,...,QLD; NSW; TAS; VIC; WA; SA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,1,0,1,1,1,1,1
2,66223.0,Halicampus mataafae,Samoan Pipefish,Least Concerned,Listed,Species or species habitat may occur,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,...,QLD; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,0,1,0,0,0,0
3,1047.0,Procellaria cinerea,Grey Petrel,Near Threatened,Listed,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Procellariidae,Procellariiformes,...,TAS; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,0,0,0,1,0,0
4,1090.0,Parahydrophis mertoni,"Arafura Smooth Sea Snake, Northern Mangrove Se...",Data Deficient,Listed,Species or species habitat may occur,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,...,NT; QLD; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,1,1,0,0,0,0
5,66705.0,Hippocampus minotaur,Bullneck Seahorse,Data Deficient,Listed,Species or species habitat may occur,2/15/2024 12:00:00 AM,fishes,Syngnathidae,Syngnathiformes,...,NSW; TAS; VIC; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,1,0,0,0,1,1,0
6,1118.0,Aipysurus foliosquama,"Leaf-scaled Sea Snake, Leaf-scaled Seasnake",Critically Endangered,Listed,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,...,WA; ACI; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,0,0,0,0,0,1
7,1119.0,Aipysurus fuscus,Dusky Sea Snake,Endangered,Listed,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,...,NT; WA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,1,0,0,0,0,1
8,1116.0,Aipysurus duboisii,"Dubois' Sea Snake, Dubois' Seasnake, Reef Shal...",Least Concerned,Listed,Species or species habitat may occur,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,...,NT; QLD; WA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,1,1,0,0,0,1
9,1117.0,Aipysurus eydouxii,Spine-tailed Sea Snake,Least Concerned,Listed,Species or species habitat may occur,2/15/2024 12:00:00 AM,reptiles,Elapidae,Squamata,...,NT; QLD; WA; CMA,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,1,1,0,0,0,1

In [33]:
# convert to date time
df_combined_marine_nodups_iucn['EXTRACT_DATE'] = pd.to_datetime(df_combined_marine_nodups_iucn['EXTRACT_DATE'])

# extract year from Extract Date (the date was "2024-02-15")
df_combined_marine_nodups_iucn['YEAR'] = df_combined_marine_nodups_iucn['EXTRACT_DATE'].dt.year

In [34]:
df_combined_marine_nodups_iucn.head()

,LISTED_TAXON_ID,SCIENTIFIC_NAME,VERNACULAR_NAME,THREATENED_STATUS,MARINE,EXTRACT_DATE,TAXON_GROUP,TAXON_FAMILY,TAXON_ORDER,TAXON_CLASS,...,SPRAT_PROFILE,ACT,NSW,NT,QLD,SA,TAS,VIC,WA,YEAR
0,66237,Hippocampus kuda,"Spotted Seahorse, Yellow Seahorse",Vulnerable,Listed,2024-02-15,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,1,1,1,0,0,0,1,2024
1,66223,Halicampus mataafae,Samoan Pipefish,Least Concerned,Listed,2024-02-15,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,0,1,0,0,0,0,2024
2,1090,Parahydrophis mertoni,"Arafura Smooth Sea Snake, Northern Mangrove Se...",Data Deficient,Listed,2024-02-15,reptiles,Elapidae,Squamata,Reptilia,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,1,1,0,0,0,0,2024
3,66705,Hippocampus minotaur,Bullneck Seahorse,Data Deficient,Listed,2024-02-15,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,1,0,0,0,1,1,0,2024
4,1118,Aipysurus foliosquama,"Leaf-scaled Sea Snake, Leaf-scaled Seasnake",Critically Endangered,Listed,2024-02-15,reptiles,Elapidae,Squamata,Reptilia,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,0,0,0,0,0,1,2024

In [61]:
# dropping columns again
df_combined_marine_nodups_iucn = df_combined_marine_nodups_iucn.drop(columns = ['REGIONS','EXTRACT_DATE'])

In [62]:
#remove row with 'Data Deficient', 'Least Concerned' and 'Near Threatened'
df_combined_marine_nodups_iucn = df_combined_marine_nodups_iucn[
                                                        (df_combined_marine_nodups_iucn['THREATENED_STATUS']!= 'Data Deficient') &
                                                        (df_combined_marine_nodups_iucn['THREATENED_STATUS']!= 'Least Concerned') & 
                                                        (df_combined_marine_nodups_iucn['THREATENED_STATUS']!= 'Near Threatened')
                                                        ]

In [63]:
df_combined_marine_nodups_iucn.head(60)

,LISTED_TAXON_ID,SCIENTIFIC_NAME,VERNACULAR_NAME,THREATENED_STATUS,MARINE,TAXON_GROUP,TAXON_FAMILY,TAXON_ORDER,TAXON_CLASS,TAXON_PHYLUM,...,SPRAT_PROFILE,ACT,NSW,NT,QLD,SA,TAS,VIC,WA,YEAR
0,66237,Hippocampus kuda,"Spotted Seahorse, Yellow Seahorse",Vulnerable,Listed,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,1,1,1,0,0,0,1,2024
4,1118,Aipysurus foliosquama,"Leaf-scaled Sea Snake, Leaf-scaled Seasnake",Critically Endangered,Listed,reptiles,Elapidae,Squamata,Reptilia,Chordata,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,0,0,0,0,0,1,2024
5,1119,Aipysurus fuscus,Dusky Sea Snake,Endangered,Listed,reptiles,Elapidae,Squamata,Reptilia,Chordata,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,1,0,0,0,0,1,2024
10,1115,Aipysurus apraefrontalis,"Short-nosed Sea Snake, Short-nosed Seasnake",Critically Endangered,Listed,reptiles,Elapidae,Squamata,Reptilia,Chordata,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,0,0,0,0,0,1,2024
14,66723,Hippocampus kelloggi,"Kellogg's Seahorse, Great Seahorse",Vulnerable,Listed,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,1,0,1,0,0,0,0,2024
29,22,Neophoca cinerea,"Australian Sea-lion, Australian Sea Lion",Endangered,Listed,mammals,Otariidae,Pinnipedia,Mammalia,Chordata,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,0,0,1,0,0,1,2024
30,26,Mirounga leonina,Southern Elephant Seal,Vulnerable,Listed,mammals,Phocidae,Pinnipedia,Mammalia,Chordata,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,1,0,0,1,1,1,1,2024
31,28,Dugong dugon,Dugong,Vulnerable,Listed,mammals,Dugongidae,Sirenia,Mammalia,Chordata,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,1,1,1,0,0,0,1,2024
61,66236,Hippocampus histrix,"Spiny Seahorse, Thorny Seahorse",Vulnerable,Listed,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,1,1,0,0,0,1,2024
63,66239,Hippocampus spinosissimus,Hedgehog Seahorse,Vulnerable,Listed,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,1,1,0,0,0,1,2024
64,66240,Hippocampus whitei,"White's Seahorse, Crowned Seahorse, Sydney Sea...",Endangered,Listed,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,1,0,1,0,1,1,0,2024
118,1768,Dermochelys coriacea,"Leatherback Turtle, Leathery Turtle, Luth",Endangered,Listed,reptiles,Dermochelyidae,Testudines,Reptilia,Chordata,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,1,1,1,1,1,1,1,2024
121,1765,Chelonia mydas,Green Turtle,Vulnerable,Listed,reptiles,Cheloniidae,Testudines,Reptilia,Chordata,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,1,1,1,1,1,1,1,2024
122,1766,Eretmochelys imbricata,Hawksbill Turtle,Vulnerable,Listed,reptiles,Cheloniidae,Testudines,Reptilia,Chordata,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,1,1,1,0,1,1,1,2024
123,1763,Caretta caretta,Loggerhead Turtle,Endangered,Listed,reptiles,Cheloniidae,Testudines,Reptilia,Chordata,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,1,1,1,1,1,1,1,2024
124,1767,Lepidochelys olivacea,"Olive Ridley Turtle, Pacific Ridley Turtle",Endangered,Listed,reptiles,Cheloniidae,Testudines,Reptilia,Chordata,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,1,1,1,0,0,0,1,2024
133,66720,Hippocampus trimaculatus,"Three-spot Seahorse, Low-crowned Seahorse, Fla...",Vulnerable,Listed,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,1,1,1,0,0,0,1,2024
136,59257,Natator depressus,Flatback Turtle,Vulnerable,Listed,reptiles,Cheloniidae,Testudines,Reptilia,Chordata,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,1,1,1,0,0,0,1,2024
146,25909,Arctocephalus tropicalis,Subantarctic Fur-seal,Endangered,Listed,mammals,Otariidae,Pinnipedia,Mammalia,Chordata,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,0,0,0,1,1,1,1,1,2024

In [64]:
# Create a dataframe : total_threat_count_data - this dataframe contains of the total count of endangered species per states and then counts 
# of each individual status counts per state

regions = ['ACT', 'NSW', 'NT', 'QLD', 'SA', 'TAS', 'VIC', 'WA'] - defined above

# Initialize summary DataFrame
total_threat_count_data = {'State': regions, 
                           'Total_Threatened_Count': [], 
                           'Critically_Endangered': [], 
                           'Vulnerable': [], 
                           'Endangered': []
                          } 

# Populate the summary DataFrame
for region in regions:
    total_threatened_count = df_combined_marine_nodups_iucn[df_combined_marine_nodups_iucn[region] == 1].shape[0]
    critically_endangered = df_combined_marine_nodups_iucn[(df_combined_marine_nodups_iucn[region] == 1) & (df_combined_marine_nodups_iucn['THREATENED_STATUS'] == 'Critically Endangered')].shape[0]
    vulnerable = df_combined_marine_nodups_iucn[(df_combined_marine_nodups_iucn[region] == 1) & (df_combined_marine_nodups_iucn['THREATENED_STATUS'] == 'Vulnerable')].shape[0]
    endangered = df_combined_marine_nodups_iucn[(df_combined_marine_nodups_iucn[region] == 1) & (df_combined_marine_nodups_iucn['THREATENED_STATUS'] == 'Endangered')].shape[0]

    total_threat_count_data['Total_Threatened_Count'].append(total_threatened_count)
    total_threat_count_data['Critically_Endangered'].append(critically_endangered)
    total_threat_count_data['Vulnerable'].append(vulnerable)
    total_threat_count_data['Endangered'].append(endangered)
  
# Convert summary_data to DataFrame
total_threat_count_data = pd.DataFrame(total_threat_count_data)

# Display the summary DataFrame
total_threat_count_data

  State  Total_Threatened_Count  Critically_Endangered  Vulnerable  Endangered
0   ACT                       0                      0           0           0
1   NSW                      12                      0           8           4
2    NT                      12                      0           8           4
3   QLD                      14                      0           9           5
4    SA                       6                      0           2           4
5   TAS                       7                      0           3           4
6   VIC                       7                      0           3           4
7    WA                      17                      2           9           6

In [65]:
total_threat_count_data.to_csv('final_threat_count_per_state.csv', index=False)

# Finding Narrative Text

In [74]:
def clean_html(raw_html):
    """
    Function for removing HTML tags from a string and decoding HTML entities.
    And to handle cases where the input is not a string.
    """
    if isinstance(raw_html, str):
        # Remove HTML tags
        clean_text = re.sub(r'<.*?>', '', raw_html)
         # Decode HTML entities
        clean_text = html.unescape(clean_text) 
        return clean_text
    return raw_html

In [70]:

def fetch_species_narrative(species_name, token):
    """
    Function to find out the narrative about threats and habitats to each species    
    """
    api_url =f"https://apiv3.iucnredlist.org/api/v3/species/narrative/{species_name}?token={token}"
    try:
         response = requests.get(api_url, timeout=10)
         response.raise_for_status()
        
         species_data = response.json()
         if 'result' in species_data and species_data['result']:
             result = species_data['result'][0]
             
             # Clean the habitat field
             raw_habitat = result.get('habitat', '')
             clean_habitat = clean_html(raw_habitat)

             raw_threats = result.get('threats', '')
             clean_threats = clean_html(raw_threats)
             
             # Filter results based on the scientific names in the DataFrame
             
        # Return the relevant fields
             return {
                 'scientificName': result.get('name',species_name),
                 'populationtrend': result.get('populationtrend'), 
                 'habitat': clean_habitat,
                 'threats': clean_threats
             }
             
         else:
             print(f"No result found for {species_name}")
             return None
            
    except requests.exceptions.HTTPError as http_err:
        print(f"HTTP error occurred: {http_err}")
        
    except requests.exceptions.ConnectionError as conn_err:
        print(f"Connection error occurred: {conn_err}")
        
    except requests.exceptions.Timeout as timeout_err:
        print(f"Timeout error occurred: {timeout_err}")
        
    except requests.exceptions.RequestException as req_err:
        print(f"An error occurred: {req_err}")
    return []

In [75]:
# List to store fetched data
species_narratives = []

# Loop through each scientific name in your DataFrame
for each_name in scientific_names:
    species_data_narrative = fetch_species_narrative(each_name, token)
    if species_data_narrative:
        species_narratives.append(species_data_narrative)
    #else:
        # If no data found or error, append a row with None or empty values
        fetched_data_final_status.append({
            'scientificName': each_name,
            'category': None
        })

# Convert the fetched data list to a DataFrame
fetched_species_df_narrative = pd.DataFrame(species_narratives)

No result found for Phalacrocorax purpurascens
No result found for Diomedea gibsoni
No result found for Enhydrina schistosa
No result found for Ephalophis greyi
No result found for Astrotia stokesii
No result found for Disteira kingii
No result found for Disteira major
No result found for Eudyptes chrysolophus sensu lato
No result found for Sterna albifrons
No result found for Sterna anaethetus
No result found for Sterna bengalensis
No result found for Sterna bergii
No result found for Puffinus carneipes
No result found for Doryrhamphus dactyliophorus
No result found for Sterna fuscata
No result found for Puffinus griseus
No result found for Puffinus pacificus
No result found for Puffinus tenuirostris
No result found for Sterna nereis
No result found for Anous tenuirostris melanops
No result found for Phaethon lepturus fulvus
No result found for Sterna caspia
No result found for Acalyptophis peronii
No result found for Doryrhamphus multiannulatus
No result found for Heteroscelus brevipes
No result found for Procelsterna cerulea
No result found for Thalassarche sp. nov.
No result found for Lapemis hardwickii
No result found for Phalacrocorax nivalis
No result found for Doryrhamphus baldwini
No result found for Heteroscelus incanus
No result found for Hydrophis mcdowelli
No result found for Pelamis platurus
     scientificName populationtrend  \
0  Hippocampus kuda      decreasing

                                             habitat  \
0  Hippocampus kuda is found in shallow inshore w...

                                             threats
0  In general, incidental capture in shrimp trawl...

In [ ]:
# Display the filtered data
print(fetched_species_df_narrative.head(1))

In [78]:
fetched_species_df_narrative.count()

scientificName     225
populationtrend    224
habitat            224
threats            224
dtype: int64

In [97]:
fetched_species_df_narrative.rename(columns={'scientificName': 'SCIENTIFIC_NAME'}, inplace=True)

In [98]:
# converting the dataframe to CSV
fetched_species_df_narrative.to_csv('narrative_data.csv', index=False)

# Merging data - main species and narrative text data

In [66]:
#df_combined_marine_nodups_iucn
narrative_df = pd.read_csv("narrative_data.csv")

In [67]:
# Adding columns to the df_combined_marine_nodups_iucn from above 

df_combined_marine_nodups_iucn_FINAL_MARGE =  pd.merge(df_combined_marine_nodups_iucn, narrative_df, on='SCIENTIFIC_NAME')

In [68]:
df_combined_marine_nodups_iucn_FINAL_MARGE.head()

,LISTED_TAXON_ID,SCIENTIFIC_NAME,VERNACULAR_NAME,THREATENED_STATUS,MARINE,TAXON_GROUP,TAXON_FAMILY,TAXON_ORDER,TAXON_CLASS,TAXON_PHYLUM,...,NT,QLD,SA,TAS,VIC,WA,YEAR,populationtrend,habitat,threats
0,66237,Hippocampus kuda,"Spotted Seahorse, Yellow Seahorse",Vulnerable,Listed,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,...,1,1,0,0,0,1,2024,decreasing,Hippocampus kuda is found in shallow inshore w...,"In general, incidental capture in shrimp trawl..."
1,1118,Aipysurus foliosquama,"Leaf-scaled Sea Snake, Leaf-scaled Seasnake",Critically Endangered,Listed,reptiles,Elapidae,Squamata,Reptilia,Chordata,...,0,0,0,0,0,1,2024,unknown,Aipysurus foliosquama is described as a tropic...,Coastal habitats in northwest Australia are th...
2,1119,Aipysurus fuscus,Dusky Sea Snake,Endangered,Listed,reptiles,Elapidae,Squamata,Reptilia,Chordata,...,1,0,0,0,0,1,2024,decreasing,A. fuscus occurs in a range of reef habitats a...,"There are no specific, clearly identified or q..."
3,1115,Aipysurus apraefrontalis,"Short-nosed Sea Snake, Short-nosed Seasnake",Critically Endangered,Listed,reptiles,Elapidae,Squamata,Reptilia,Chordata,...,0,0,0,0,0,1,2024,unknown,"At Ashmore, this sea snake species was found o...",There have been severe declines in the Aipysur...
4,66723,Hippocampus kelloggi,"Kellogg's Seahorse, Great Seahorse",Vulnerable,Listed,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,...,0,1,0,0,0,0,2024,decreasing,Hippocampus kelloggi is most commonly associat...,Hipocampus kelloggi is threatened from bycatch...

In [58]:
# removing some columns from the datasets
df_combined_marine_nodups_iucn_FINAL_MARGE = df_combined_marine_nodups_iucn_FINAL_MARGE.drop(columns=["EXTRACT_DATE","REGIONS"])

,LISTED_TAXON_ID,SCIENTIFIC_NAME,VERNACULAR_NAME,THREATENED_STATUS,MARINE,TAXON_GROUP,TAXON_FAMILY,TAXON_ORDER,TAXON_CLASS,TAXON_PHYLUM,...,NT,QLD,SA,TAS,VIC,WA,YEAR,populationtrend,habitat,threats
0,66237,Hippocampus kuda,"Spotted Seahorse, Yellow Seahorse",Vulnerable,Listed,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,...,1,1,0,0,0,1,2024,decreasing,Hippocampus kuda is found in shallow inshore w...,"In general, incidental capture in shrimp trawl..."
1,1118,Aipysurus foliosquama,"Leaf-scaled Sea Snake, Leaf-scaled Seasnake",Critically Endangered,Listed,reptiles,Elapidae,Squamata,Reptilia,Chordata,...,0,0,0,0,0,1,2024,unknown,Aipysurus foliosquama is described as a tropic...,Coastal habitats in northwest Australia are th...
2,1119,Aipysurus fuscus,Dusky Sea Snake,Endangered,Listed,reptiles,Elapidae,Squamata,Reptilia,Chordata,...,1,0,0,0,0,1,2024,decreasing,A. fuscus occurs in a range of reef habitats a...,"There are no specific, clearly identified or q..."
3,1115,Aipysurus apraefrontalis,"Short-nosed Sea Snake, Short-nosed Seasnake",Critically Endangered,Listed,reptiles,Elapidae,Squamata,Reptilia,Chordata,...,0,0,0,0,0,1,2024,unknown,"At Ashmore, this sea snake species was found o...",There have been severe declines in the Aipysur...
4,66723,Hippocampus kelloggi,"Kellogg's Seahorse, Great Seahorse",Vulnerable,Listed,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,...,0,1,0,0,0,0,2024,decreasing,Hippocampus kelloggi is most commonly associat...,Hipocampus kelloggi is threatened from bycatch...
5,22,Neophoca cinerea,"Australian Sea-lion, Australian Sea Lion",Endangered,Listed,mammals,Otariidae,Pinnipedia,Mammalia,Chordata,...,0,0,1,0,0,1,2024,decreasing,"Australian Sea Lions are sexually dimorphic, w...","Although now protected, Australian Sea Lions h..."
6,26,Mirounga leonina,Southern Elephant Seal,Vulnerable,Listed,mammals,Phocidae,Pinnipedia,Mammalia,Chordata,...,0,0,1,1,1,1,2024,stable,Southern Elephant Seals are the largest of all...,Southern Elephant Seals face few threats and c...
7,28,Dugong dugon,Dugong,Vulnerable,Listed,mammals,Dugongidae,Sirenia,Mammalia,Chordata,...,1,1,0,0,0,1,2024,decreasing,Habitat requirements for Dugongs include coast...,Threats to Dugongs vary between different popu...
8,66236,Hippocampus histrix,"Spiny Seahorse, Thorny Seahorse",Vulnerable,Listed,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,...,1,1,0,0,0,1,2024,decreasing,Hippocampus histrix is found at depths between...,The major threat to Hippocampus histrix is ove...
9,66239,Hippocampus spinosissimus,Hedgehog Seahorse,Vulnerable,Listed,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,...,1,1,0,0,0,1,2024,decreasing,Hippocampus spinosissimus are found in reef sy...,Hippocampus spinosissimus is threatened from b...
10,66240,Hippocampus whitei,"White's Seahorse, Crowned Seahorse, Sydney Sea...",Endangered,Listed,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,...,0,1,0,1,1,0,2024,decreasing,Hippocampus whitei is known to occur at depths...,The major threat to Hippocampus whitei is loss...
11,1768,Dermochelys coriacea,"Leatherback Turtle, Leathery Turtle, Luth",Endangered,Listed,reptiles,Dermochelyidae,Testudines,Reptilia,Chordata,...,1,1,1,1,1,1,2024,decreasing,"D. coriacea is an oceanic, deep-diving marine ...",Threats to Leatherbacks vary in time and space...
12,1765,Chelonia mydas,Green Turtle,Vulnerable,Listed,reptiles,Cheloniidae,Testudines,Reptilia,Chordata,...,1,1,1,1,1,1,2024,decreasing,"Like most sea turtles, green turtles are highl...","Green turtles, like other sea turtle species, ..."
13,1766,Eretmochelys imbricata,Hawksbill Turtle,Vulnerable,Listed,reptiles,Cheloniidae,Testudines,Reptilia,Chordata,...,1,1,0,1,1,1,2024,decreasing,HabitatsHawksbills nest on insular and mainlan...,Threats: The most important threats to Hawksbi...
14,1763,Caretta caretta,Loggerhead Turtle,Endangered,Listed,reptiles,Cheloniidae,Testudines,Reptilia,Chordata,...,1,1,1,1,1,1,2024,decreasing,The Loggerhead Turtle nests on insular and mai...,"Threats to Loggerheads vary in time and space,..."
15,1767,Lepidochelys olivacea,"Olive Ridley Turtle, Pacific Ridley Turtle",Endangered,Listed,reptiles,Cheloniidae,Testudines,Reptilia,Chordata,...,1,1,0,0,0,1,2024,decreasing,"HabitatsLike most other sea turtles, Olive Rid...","Like other long-lived species, Olive Ridleys a..."
16,66720,Hippocampus trimaculatus,"Three-spot Seahorse, Low-crowned Seahorse, Fla...",Vulnerable,Listed,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,Chordata,...,1,1,0,0,0,1,2024,decreasing,Hippocampus trimaculatus is most often found a...,The primary threat to Hippocampus trimaculatus...
17,59257,Natator depressus,Flatback Turtle,Vulnerable,Listed,reptiles,Cheloniidae,Testudines,Reptilia,Chordata,...,1,1,0,0,0,1,2024,NaN,Terrestrial nest sites,NaN
18,25909,Arctocephalus tropicalis,Subantarctic Fur-seal,Endangered,Listed,mammals,Otariidae,Pinnipedia,Mammalia,Chordata,...,0,1,1,1,1,1,2024,stable,"Subantarctic Fur Seals are sexually dimorphic,...",Similar to all of the other southern Fur Seals...

In [59]:
df_combined_marine_nodups_iucn_FINAL_MARGE.head()

,LISTED_TAXON_ID,SCIENTIFIC_NAME,VERNACULAR_NAME,THREATENED_STATUS,MARINE,EXTRACT_DATE,TAXON_GROUP,TAXON_FAMILY,TAXON_ORDER,TAXON_CLASS,...,NT,QLD,SA,TAS,VIC,WA,YEAR,populationtrend,habitat,threats
0,66237,Hippocampus kuda,"Spotted Seahorse, Yellow Seahorse",Vulnerable,Listed,2024-02-15,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,...,1,1,0,0,0,1,2024,decreasing,Hippocampus kuda is found in shallow inshore w...,"In general, incidental capture in shrimp trawl..."
1,1118,Aipysurus foliosquama,"Leaf-scaled Sea Snake, Leaf-scaled Seasnake",Critically Endangered,Listed,2024-02-15,reptiles,Elapidae,Squamata,Reptilia,...,0,0,0,0,0,1,2024,unknown,Aipysurus foliosquama is described as a tropic...,Coastal habitats in northwest Australia are th...
2,1119,Aipysurus fuscus,Dusky Sea Snake,Endangered,Listed,2024-02-15,reptiles,Elapidae,Squamata,Reptilia,...,1,0,0,0,0,1,2024,decreasing,A. fuscus occurs in a range of reef habitats a...,"There are no specific, clearly identified or q..."
3,1115,Aipysurus apraefrontalis,"Short-nosed Sea Snake, Short-nosed Seasnake",Critically Endangered,Listed,2024-02-15,reptiles,Elapidae,Squamata,Reptilia,...,0,0,0,0,0,1,2024,unknown,"At Ashmore, this sea snake species was found o...",There have been severe declines in the Aipysur...
4,66723,Hippocampus kelloggi,"Kellogg's Seahorse, Great Seahorse",Vulnerable,Listed,2024-02-15,fishes,Syngnathidae,Syngnathiformes,Actinopterygii,...,0,1,0,0,0,0,2024,decreasing,Hippocampus kelloggi is most commonly associat...,Hipocampus kelloggi is threatened from bycatch...

In [69]:
df_combined_marine_nodups_iucn_FINAL_MARGE.to_csv('final_threat.csv', index=False)

## =========================================================================

# Cleaning and Wrangling Threatened Species State CSV

In [9]:
threat_state_df.head()

,Scientific Name,Common Name,Current Scientific Name,Threatened status,ACT,NSW,NT,QLD,SA,TAS,...,Profile,Date extracted,NSL Name,Family,Genus,Species,Infraspecific Rank,Infraspecies,Species Author,Infraspecies Author
0,Abutilon julianae,Norfolk Island Abutilon,-,Critically Endangered,-,-,-,-,-,-,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,2024-Jul-24,https://id.biodiversity.org.au/name/apni/56543,Malvaceae,Abutilon,julianae,-,-,Endl.,-
1,Acacia ammophila,-,-,Vulnerable,-,-,-,Yes,-,-,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,2024-Jul-24,https://id.biodiversity.org.au/name/apni/58340,Fabaceae,Acacia,ammophila,-,-,Pedley,-
2,Acacia anomala,"Grass Wattle, Chittering Grass Wattle",-,Vulnerable,-,-,-,-,-,-,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,2024-Jul-24,https://id.biodiversity.org.au/name/apni/58556,Fabaceae,Acacia,anomala,-,-,C.A.Gardner ex Court,-
3,Acacia aphylla,Leafless Rock Wattle,-,Vulnerable,-,-,-,-,-,-,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,2024-Jul-24,https://id.biodiversity.org.au/name/apni/58565,Fabaceae,Acacia,aphylla,-,-,Maslin,-
4,Acacia aprica,Blunt Wattle,-,Endangered,-,-,-,-,-,-,...,http://www.environment.gov.au/cgi-bin/sprat/pu...,2024-Jul-24,https://id.biodiversity.org.au/name/apni/149911,Fabaceae,Acacia,aprica,-,-,Maslin A.R.Chapman,-

In [10]:
# Removing Unnecessary Columns

cols_threat_state = ["ACI","CKI","CI","CSI","JBT","NFI","HMI","AAT","CMA","Current SPRAT TaxonID","Kingdom","Class","Profile","Date extracted","NSL Name",
               "Family","Genus","Species","Infraspecific Rank","Infraspecies","Species Author","Infraspecies Author"]

threat_state_df_filtered = threat_state_df.drop(columns=cols_threat_state)

In [11]:
threat_state_df_filtered.head()

,Scientific Name,Common Name,Current Scientific Name,Threatened status,ACT,NSW,NT,QLD,SA,TAS,VIC,WA,Listed SPRAT TaxonID
0,Abutilon julianae,Norfolk Island Abutilon,-,Critically Endangered,-,-,-,-,-,-,-,-,27797
1,Acacia ammophila,-,-,Vulnerable,-,-,-,Yes,-,-,-,-,3763
2,Acacia anomala,"Grass Wattle, Chittering Grass Wattle",-,Vulnerable,-,-,-,-,-,-,-,Yes,8153
3,Acacia aphylla,Leafless Rock Wattle,-,Vulnerable,-,-,-,-,-,-,-,Yes,13553
4,Acacia aprica,Blunt Wattle,-,Endangered,-,-,-,-,-,-,-,Yes,64821

In [12]:
threat_state_df_filtered.isnull().sum()

Scientific Name            0
Common Name                0
Current Scientific Name    0
Threatened status          0
ACT                        0
NSW                        0
NT                         0
QLD                        0
SA                         0
TAS                        0
VIC                        0
WA                         0
Listed SPRAT TaxonID       0
dtype: int64

In [38]:
threat_state_df_filtered.count()

SCIENTIFIC_NAME            2118
Common Name                2118
Current Scientific Name    2118
Threatened status          2118
ACT                        2118
NSW                        2118
NT                         2118
QLD                        2118
SA                         2118
TAS                        2118
VIC                        2118
WA                         2118
Listed SPRAT TaxonID       2118
dtype: int64

In [13]:
# Replacing Values in state columns "-" to 0 and "Yes" to 1

cols_replace_value = ["ACT","NSW","NT","QLD","SA","TAS","VIC","WA"]

threat_state_df_filtered[cols_replace_value] = threat_state_df_filtered[cols_replace_value].replace({'-': 0, 'Yes': 1})

In [14]:
threat_state_df_filtered.head()

,Scientific Name,Common Name,Current Scientific Name,Threatened status,ACT,NSW,NT,QLD,SA,TAS,VIC,WA,Listed SPRAT TaxonID
0,Abutilon julianae,Norfolk Island Abutilon,-,Critically Endangered,0,0,0,0,0,0,0,0,27797
1,Acacia ammophila,-,-,Vulnerable,0,0,0,1,0,0,0,0,3763
2,Acacia anomala,"Grass Wattle, Chittering Grass Wattle",-,Vulnerable,0,0,0,0,0,0,0,1,8153
3,Acacia aphylla,Leafless Rock Wattle,-,Vulnerable,0,0,0,0,0,0,0,1,13553
4,Acacia aprica,Blunt Wattle,-,Endangered,0,0,0,0,0,0,0,1,64821

In [15]:
threat_state_df_filtered.count()

Scientific Name            2118
Common Name                2118
Current Scientific Name    2118
Threatened status          2118
ACT                        2118
NSW                        2118
NT                         2118
QLD                        2118
SA                         2118
TAS                        2118
VIC                        2118
WA                         2118
Listed SPRAT TaxonID       2118
dtype: int64

In [39]:
# Rename a column 
threat_state_df_filtered.rename(columns={'Scientific Name': 'SCIENTIFIC_NAME', "Listed SPRAT TaxonID": "LISTED_TAXON_ID"}, inplace=True)

## =========================================================================

# Joining Two Dataset

In [40]:
df_combined =  pd.merge(threat_df_filtered_marine_nodups, threat_state_df_filtered, on='LISTED_TAXON_ID')

In [41]:
df_combined.count()

LISTED_TAXON_ID            41
SCIENTIFIC_NAME_x          41
VERNACULAR_NAME            41
THREATENED_STATUS          41
MARINE                     41
PRESENCE_RANK              41
PRESENCE_CATEGORY          41
EXTRACT_DATE               41
TAXON_GROUP                41
TAXON_FAMILY               41
TAXON_ORDER                41
TAXON_CLASS                41
TAXON_PHYLUM               41
TAXON_KINGDOM              41
REGIONS                    41
GlobalID                   41
SCIENTIFIC_NAME_y          41
Common Name                41
Current Scientific Name    41
Threatened status          41
ACT                        41
NSW                        41
NT                         41
QLD                        41
SA                         41
TAS                        41
VIC                        41
WA                         41
dtype: int64

In [37]:
df_combined.head(41)

,LISTED_TAXON_ID,SCIENTIFIC_NAME,VERNACULAR_NAME,THREATENED_STATUS,MARINE,PRESENCE_RANK,PRESENCE_CATEGORY,EXTRACT_DATE,TAXON_GROUP,TAXON_FAMILY,...,Threatened status,ACT,NSW,NT,QLD,SA,TAS,VIC,WA,Listed SPRAT TaxonID
0,1118,Aipysurus foliosquama,"Leaf-scaled Sea Snake, Leaf-scaled Seasnake",Critically Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,reptiles,Elapidae,...,Critically Endangered,0,0,0,0,0,0,0,1,1118
1,64462,Thalassarche steadi,White-capped Albatross,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Vulnerable,0,1,0,1,1,1,1,1,64462
2,64463,Thalassarche salvini,Salvin's Albatross,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Vulnerable,0,1,0,1,1,1,1,0,64463
3,64464,Thalassarche carteri,Indian Yellow-nosed Albatross,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Vulnerable,0,0,0,1,1,0,1,1,64464
4,1115,Aipysurus apraefrontalis,"Short-nosed Sea Snake, Short-nosed Seasnake",Critically Endangered,Listed,1,Species or species habitat may occur,2/15/2024 12:00:00 AM,reptiles,Elapidae,...,Critically Endangered,0,0,0,0,0,0,0,1,1115
5,89221,Diomedea epomophora,Southern Royal Albatross,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Vulnerable,0,1,0,1,1,1,1,1,89221
6,89223,Diomedea exulans,Wandering Albatross,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Vulnerable,0,1,0,1,1,1,1,1,89223
7,89224,Thalassarche cauta,Shy Albatross,Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Endangered,0,1,0,1,1,1,1,1,89224
8,22,Neophoca cinerea,"Australian Sea-lion, Australian Sea Lion",Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,mammals,Otariidae,...,Endangered,0,0,0,0,1,0,0,1,22
9,26,Mirounga leonina,Southern Elephant Seal,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,mammals,Phocidae,...,Vulnerable,0,0,0,0,1,1,0,0,26
10,874,Calidris acuminata,Sharp-tailed Sandpiper,Vulnerable,Listed,1,Species or species habitat may occur,2/15/2024 12:00:00 AM,birds,Scolopacidae,...,Vulnerable,1,1,1,1,1,1,1,1,874
11,877,Charadrius leschenaultii,"Greater Sand Plover, Large Sand Plover",Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Charadriidae,...,Vulnerable,0,1,1,1,1,1,1,1,877
12,1060,Macronectes giganteus,"Southern Giant-Petrel, Southern Giant Petrel",Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Procellariidae,...,Endangered,0,1,0,1,1,1,1,1,1060
13,1061,Macronectes halli,Northern Giant Petrel,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Procellariidae,...,Vulnerable,0,1,0,1,1,1,1,1,1061
14,66240,Hippocampus whitei,"White's Seahorse, Crowned Seahorse, Sydney Sea...",Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,fishes,Syngnathidae,...,Endangered,0,1,0,1,0,1,1,0,66240
15,847,Numenius madagascariensis,"Eastern Curlew, Far Eastern Curlew",Critically Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Scolopacidae,...,Critically Endangered,0,1,1,1,1,1,1,1,847
16,66471,Diomedea dabbenena,Tristan Albatross,Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Endangered,0,1,0,1,1,1,1,1,66471
17,66472,Thalassarche melanophris,Black-browed Albatross,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Vulnerable,0,1,0,1,1,1,1,1,66472
18,872,Arenaria interpres,Ruddy Turnstone,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Scolopacidae,...,Vulnerable,0,1,1,1,1,1,1,1,872
19,66491,Thalassarche chrysostoma,Grey-headed Albatross,Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Endangered,0,1,0,1,1,1,1,1,66491
20,1036,Pterodroma mollis,Soft-plumaged Petrel,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Procellariidae,...,Vulnerable,0,0,0,0,1,1,1,1,1036
21,879,Charadrius mongolus,"Lesser Sand Plover, Mongolian Plover",Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Charadriidae,...,Endangered,0,1,1,1,1,1,1,1,879
22,1059,Halobaena caerulea,Blue Petrel,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Procellariidae,...,Vulnerable,0,1,0,0,1,1,1,1,1059
23,1011,Fregata andrewsi,"Christmas Island Frigatebird, Andrew's Frigate...",Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Fregatidae,...,Endangered,0,0,0,0,0,0,0,0,1011
24,1768,Dermochelys coriacea,"Leatherback Turtle, Leathery Turtle, Luth",Endangered,Listed,1,Species or species habitat may occur,2/15/2024 12:00:00 AM,reptiles,Dermochelyidae,...,Endangered,0,1,1,1,1,1,1,1,1768
25,26000,Anous tenuirostris melanops,Australian Lesser Noddy,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Laridae,...,Vulnerable,0,0,0,0,0,0,0,1,26000
26,1765,Chelonia mydas,Green Turtle,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,reptiles,Cheloniidae,...,Vulnerable,0,1,1,1,1,1,1,1,1765
27,1766,Eretmochelys imbricata,Hawksbill Turtle,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,reptiles,Cheloniidae,...,Vulnerable,0,1,1,1,0,1,1,1,1766
28,1763,Caretta caretta,Loggerhead Turtle,Endangered,Listed,1,Species or species habitat may occur,2/15/2024 12:00:00 AM,reptiles,Cheloniidae,...,Endangered,0,1,1,1,1,1,1,1,1763
29,26021,Phaethon lepturus fulvus,"Christmas Island White-tailed Tropicbird, Gold...",Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Phaethontidae,...,Endangered,0,0,0,0,0,0,0,0,26021
30,64459,Thalassarche impavida,"Campbell Albatross, Campbell Black-browed Alba...",Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Vulnerable,0,1,0,1,1,1,1,1,64459
31,1767,Lepidochelys olivacea,"Olive Ridley Turtle, Pacific Ridley Turtle",Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,reptiles,Cheloniidae,...,Endangered,0,1,1,1,0,0,0,1,1767
32,59297,Papasula abbotti,Abbott's Booby,Endangered,Listed,1,Species or species habitat may occur,2/15/2024 12:00:00 AM,birds,Sulidae,...,Endangered,0,0,0,0,0,0,0,0,59297
33,64456,Diomedea sanfordi,Northern Royal Albatross,Endangered,Listed,1,Species or species habitat may occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Endangered,0,1,0,1,1,1,1,1,64456
34,64457,Thalassarche eremita,Chatham Albatross,Endangered,Listed,1,Species or species habitat may occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Endangered,0,1,0,1,0,1,1,0,64457
35,64458,Diomedea antipodensis,Antipodean Albatross,Vulnerable,Listed,1,Species or species habitat may occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Vulnerable,0,1,0,1,1,1,1,1,64458
36,64460,Thalassarche bulleri,"Buller's Albatross, Pacific Albatross",Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Vulnerable,0,1,0,1,1,1,1,0,64460
37,59257,Natator depressus,Flatback Turtle,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,reptiles,Cheloniidae,...,Vulnerable,0,1,1,1,0,0,0,1,59257
38,64405,Diomedea amsterdamensis,Amsterdam Albatross,Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Endangered,0,1,0,0,1,1,1,1,64405
39,1075,Phoebetria fusca,Sooty Albatross,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Vulnerable,0,1,0,1,1,1,1,1,1075
40,25909,Arctocephalus tropicalis,Subantarctic Fur-seal,Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,mammals,Otariidae,...,Endangered,0,0,0,0,0,1,0,0,25909

In [25]:
df_combined_noduplicates = df_combined.drop_duplicates(subset="LISTED_TAXON_ID")

In [26]:
df_combined_noduplicates.count()

LISTED_TAXON_ID            41
SCIENTIFIC_NAME            41
VERNACULAR_NAME            41
THREATENED_STATUS          41
MARINE                     41
PRESENCE_RANK              41
PRESENCE_CATEGORY          41
EXTRACT_DATE               41
TAXON_GROUP                41
TAXON_FAMILY               41
TAXON_ORDER                41
TAXON_CLASS                41
TAXON_PHYLUM               41
TAXON_KINGDOM              41
GlobalID                   41
Common Name                41
Current Scientific Name    41
Threatened status          41
ACT                        41
NSW                        41
NT                         41
QLD                        41
SA                         41
TAS                        41
VIC                        41
WA                         41
Listed SPRAT TaxonID       41
dtype: int64

In [27]:
df_combined_noduplicates.head(41)

,LISTED_TAXON_ID,SCIENTIFIC_NAME,VERNACULAR_NAME,THREATENED_STATUS,MARINE,PRESENCE_RANK,PRESENCE_CATEGORY,EXTRACT_DATE,TAXON_GROUP,TAXON_FAMILY,...,Threatened status,ACT,NSW,NT,QLD,SA,TAS,VIC,WA,Listed SPRAT TaxonID
0,1118,Aipysurus foliosquama,"Leaf-scaled Sea Snake, Leaf-scaled Seasnake",Critically Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,reptiles,Elapidae,...,Critically Endangered,0,0,0,0,0,0,0,1,1118
2,64462,Thalassarche steadi,White-capped Albatross,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Vulnerable,0,1,0,1,1,1,1,1,64462
4,64463,Thalassarche salvini,Salvin's Albatross,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Vulnerable,0,1,0,1,1,1,1,0,64463
6,64464,Thalassarche carteri,Indian Yellow-nosed Albatross,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Vulnerable,0,0,0,1,1,0,1,1,64464
8,1115,Aipysurus apraefrontalis,"Short-nosed Sea Snake, Short-nosed Seasnake",Critically Endangered,Listed,1,Species or species habitat may occur,2/15/2024 12:00:00 AM,reptiles,Elapidae,...,Critically Endangered,0,0,0,0,0,0,0,1,1115
10,89221,Diomedea epomophora,Southern Royal Albatross,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Vulnerable,0,1,0,1,1,1,1,1,89221
12,89223,Diomedea exulans,Wandering Albatross,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Vulnerable,0,1,0,1,1,1,1,1,89223
14,89224,Thalassarche cauta,Shy Albatross,Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Endangered,0,1,0,1,1,1,1,1,89224
16,22,Neophoca cinerea,"Australian Sea-lion, Australian Sea Lion",Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,mammals,Otariidae,...,Endangered,0,0,0,0,1,0,0,1,22
18,26,Mirounga leonina,Southern Elephant Seal,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,mammals,Phocidae,...,Vulnerable,0,0,0,0,1,1,0,0,26
20,874,Calidris acuminata,Sharp-tailed Sandpiper,Vulnerable,Listed,1,Species or species habitat may occur,2/15/2024 12:00:00 AM,birds,Scolopacidae,...,Vulnerable,1,1,1,1,1,1,1,1,874
27,877,Charadrius leschenaultii,"Greater Sand Plover, Large Sand Plover",Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Charadriidae,...,Vulnerable,0,1,1,1,1,1,1,1,877
29,1060,Macronectes giganteus,"Southern Giant-Petrel, Southern Giant Petrel",Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Procellariidae,...,Endangered,0,1,0,1,1,1,1,1,1060
31,1061,Macronectes halli,Northern Giant Petrel,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Procellariidae,...,Vulnerable,0,1,0,1,1,1,1,1,1061
33,66240,Hippocampus whitei,"White's Seahorse, Crowned Seahorse, Sydney Sea...",Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,fishes,Syngnathidae,...,Endangered,0,1,0,1,0,1,1,0,66240
35,847,Numenius madagascariensis,"Eastern Curlew, Far Eastern Curlew",Critically Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Scolopacidae,...,Critically Endangered,0,1,1,1,1,1,1,1,847
41,66471,Diomedea dabbenena,Tristan Albatross,Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Endangered,0,1,0,1,1,1,1,1,66471
43,66472,Thalassarche melanophris,Black-browed Albatross,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Vulnerable,0,1,0,1,1,1,1,1,66472
45,872,Arenaria interpres,Ruddy Turnstone,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Scolopacidae,...,Vulnerable,0,1,1,1,1,1,1,1,872
46,66491,Thalassarche chrysostoma,Grey-headed Albatross,Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Endangered,0,1,0,1,1,1,1,1,66491
48,1036,Pterodroma mollis,Soft-plumaged Petrel,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Procellariidae,...,Vulnerable,0,0,0,0,1,1,1,1,1036
50,879,Charadrius mongolus,"Lesser Sand Plover, Mongolian Plover",Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Charadriidae,...,Endangered,0,1,1,1,1,1,1,1,879
51,1059,Halobaena caerulea,Blue Petrel,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Procellariidae,...,Vulnerable,0,1,0,0,1,1,1,1,1059
53,1011,Fregata andrewsi,"Christmas Island Frigatebird, Andrew's Frigate...",Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Fregatidae,...,Endangered,0,0,0,0,0,0,0,0,1011
54,1768,Dermochelys coriacea,"Leatherback Turtle, Leathery Turtle, Luth",Endangered,Listed,1,Species or species habitat may occur,2/15/2024 12:00:00 AM,reptiles,Dermochelyidae,...,Endangered,0,1,1,1,1,1,1,1,1768
61,26000,Anous tenuirostris melanops,Australian Lesser Noddy,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Laridae,...,Vulnerable,0,0,0,0,0,0,0,1,26000
63,1765,Chelonia mydas,Green Turtle,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,reptiles,Cheloniidae,...,Vulnerable,0,1,1,1,1,1,1,1,1765
67,1766,Eretmochelys imbricata,Hawksbill Turtle,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,reptiles,Cheloniidae,...,Vulnerable,0,1,1,1,0,1,1,1,1766
74,1763,Caretta caretta,Loggerhead Turtle,Endangered,Listed,1,Species or species habitat may occur,2/15/2024 12:00:00 AM,reptiles,Cheloniidae,...,Endangered,0,1,1,1,1,1,1,1,1763
81,26021,Phaethon lepturus fulvus,"Christmas Island White-tailed Tropicbird, Gold...",Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Phaethontidae,...,Endangered,0,0,0,0,0,0,0,0,26021
83,64459,Thalassarche impavida,"Campbell Albatross, Campbell Black-browed Alba...",Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Vulnerable,0,1,0,1,1,1,1,1,64459
85,1767,Lepidochelys olivacea,"Olive Ridley Turtle, Pacific Ridley Turtle",Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,reptiles,Cheloniidae,...,Endangered,0,1,1,1,0,0,0,1,1767
87,59297,Papasula abbotti,Abbott's Booby,Endangered,Listed,1,Species or species habitat may occur,2/15/2024 12:00:00 AM,birds,Sulidae,...,Endangered,0,0,0,0,0,0,0,0,59297
89,64456,Diomedea sanfordi,Northern Royal Albatross,Endangered,Listed,1,Species or species habitat may occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Endangered,0,1,0,1,1,1,1,1,64456
91,64457,Thalassarche eremita,Chatham Albatross,Endangered,Listed,1,Species or species habitat may occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Endangered,0,1,0,1,0,1,1,0,64457
92,64458,Diomedea antipodensis,Antipodean Albatross,Vulnerable,Listed,1,Species or species habitat may occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Vulnerable,0,1,0,1,1,1,1,1,64458
94,64460,Thalassarche bulleri,"Buller's Albatross, Pacific Albatross",Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Vulnerable,0,1,0,1,1,1,1,0,64460
96,59257,Natator depressus,Flatback Turtle,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,reptiles,Cheloniidae,...,Vulnerable,0,1,1,1,0,0,0,1,59257
99,64405,Diomedea amsterdamensis,Amsterdam Albatross,Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Endangered,0,1,0,0,1,1,1,1,64405
101,1075,Phoebetria fusca,Sooty Albatross,Vulnerable,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,birds,Diomedeidae,...,Vulnerable,0,1,0,1,1,1,1,1,1075
103,25909,Arctocephalus tropicalis,Subantarctic Fur-seal,Endangered,Listed,2,Species or species habitat likely to occur,2/15/2024 12:00:00 AM,mammals,Otariidae,...,Endangered,0,0,0,0,0,1,0,0,25909

# STATE BOUNDARY GEOJSON

In [49]:
# Opening geojson state file
with open('georef-australia-state@public.geojson', 'r') as f:
    state_data = json.load(f)

In [50]:
# Check the columns (keys) in the properties of the first feature
feature = state_data['features'][0]
columns = feature['properties'].keys()

print("Columns in the GeoJSON file:")
for column in columns:
    print(column)

Columns in the GeoJSON file:
geo_point_2d
year
ste_code
ste_name
ste_area_code
ste_type
ste_iso3166_code

In [51]:
# Important Columns
imp_cols = ["ste_name"]

In [53]:
# creating an empty list to store filtered data
filtered_states = []
for feature in state_data['features']:
    properties = feature['properties']
    if properties['ste_name'] != ["Other Territories"]:
        filtered_feature = {
            "type": "Feature",
            "properties": {key: properties[key][0] for key in imp_cols},
            "geometry": feature["geometry"]
        }
        filtered_states.append(filtered_feature)

In [55]:
# Creating the GeoJSON structure from filtered data
cleaned_states = {
    "type": "FeatureCollection",
    "features": filtered_states 
}

# Save the filtered data to a new GeoJSON file
with open('FINAL_STATE_data_new.json', 'w') as f:
    json.dump(cleaned_states, f, indent=2)